/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Santiago
 */
public class ProyectoConstruccionColombia extends javax.swing.JFrame {

    /**
     * Creates new form ProyectoConstruccionColombia
     */
    public ProyectoConstruccionColombia() {
        initComponents();
        label1.setVisible(false);
        Tablamodelo = (DefaultTableModel)this.Tabla1.getModel();
    }
    DefaultTableModel Tablamodelo;
    String url="jdbc:sqlite:C:\\Users\\Santiago\\Documents\\Santiago\\DIPLOMADO\\Programacion\\Ciclo 2\\DB\\ProyectosConstruccion.db";
    Connection conexion;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnConectar = new javax.swing.JButton();
        btnConsulta1 = new javax.swing.JButton();
        btnConsulta2 = new javax.swing.JButton();
        btnConsulta3 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Construyendo por Colombia - Consultas");
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("CONSTRUYENDO POR COLOMBIA");

        btnConectar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConectar.setText("Conectar");
        btnConectar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });

        btnConsulta1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConsulta1.setText("Consulta 1");
        btnConsulta1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulta1ActionPerformed(evt);
            }
        });

        btnConsulta2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConsulta2.setText("Consulta 2");
        btnConsulta2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsulta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulta2ActionPerformed(evt);
            }
        });

        btnConsulta3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConsulta3.setText("Consulta 3");
        btnConsulta3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsulta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulta3ActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label1.setText("jLabel2");

        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(Tabla1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label1)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnConsulta1)
                                .addGap(18, 18, 18)
                                .addComponent(btnConsulta2)
                                .addGap(18, 18, 18)
                                .addComponent(btnConsulta3)))
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsulta1)
                    .addComponent(btnConsulta2)
                    .addComponent(btnConsulta3)
                    .addComponent(btnConectar)
                    .addComponent(btnSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        try{
            conexion = DriverManager.getConnection(url);
            if(conexion!=null){
                JOptionPane.showMessageDialog(null,"Conexión exitosa!!");
            }
        }catch(Exception x){
            JOptionPane.showMessageDialog(null,"Conexión fallida","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConectarActionPerformed

    private void btnConsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulta1ActionPerformed
        label1.setVisible(true);
        label1.setText("Listado de Proyectos de la ciudad de Pereira:");
        Tablamodelo.setRowCount(0);
        Tablamodelo.setColumnCount(0);
        ResultSet result = null;
        try{
            PreparedStatement st = conexion.prepareStatement("select Constructora, Ciudad, Banco_Vinculado, Porcentaje_Cuota_Inicial, Clasificacion, Fecha_Inicio from Proyecto where Ciudad = 'Pereira'; ");
            result=st.executeQuery();
            Tablamodelo.addColumn("Constructora");
            Tablamodelo.addColumn("Ciudad");
            Tablamodelo.addColumn("Banco_Vinculado");
            Tablamodelo.addColumn("Porcentaje_Cuota_Inicial");
            Tablamodelo.addColumn("Clasificacion");
            Tablamodelo.addColumn("Fecha_Inicio");
            while(result.next()){
                Tablamodelo.addRow(new Object[]{result.getString("Constructora"),result.getString("Ciudad"),result.getString("Banco_Vinculado"),result.getString("Porcentaje_Cuota_Inicial"),result.getString("Clasificacion"),result.getString("Fecha_Inicio")});
            }
        }catch(Exception x){
            JOptionPane.showMessageDialog(null,"Conexión fallida","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConsulta1ActionPerformed

    private void btnConsulta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulta2ActionPerformed
        label1.setVisible(true);
        label1.setText("Listado de compras:");
        Tablamodelo.setRowCount(0);
        Tablamodelo.setColumnCount(0);
        ResultSet result = null;
        String consulta2 = "SELECT c.Proveedor, p.Constructora, c.Pagado  FROM Compra c\n" +
        "INNER JOIN Proyecto p\n" +
        "ON c.ID_Proyecto = p.ID_Proyecto \n" +
        "WHERE (c.Proveedor='Homecenter' or c.Proveedor='JUMBO') AND (c.Pagado ='Si' and p.Constructora LIKE '%S.A.')\n" + "ORDER BY c.Proveedor ASC;";
        try{
            PreparedStatement st = conexion.prepareStatement(consulta2);
            result=st.executeQuery();
            Tablamodelo.addColumn("Proveedor");
            Tablamodelo.addColumn("Constructora");
            Tablamodelo.addColumn("Pagado");
            while(result.next()){

                Tablamodelo.addRow(new Object[]{result.getString("Proveedor"),result.getString("Constructora"),result.getString("Pagado")});
            }
        }catch(Exception x){
            JOptionPane.showMessageDialog(null,"Conexión fallida","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConsulta2ActionPerformed

    private void btnConsulta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulta3ActionPerformed
        label1.setVisible(true);
        label1.setText("Cargo y el máximo de los Salarios:");
        Tablamodelo.setRowCount(0);
        Tablamodelo.setColumnCount(0);
        ResultSet result = null;
        try{
            PreparedStatement st = conexion.prepareStatement("SELECT l.Cargo, MAX(l.Salario) FROM Lider l GROUP BY Cargo HAVING MAX(l.Salario)>=700000;");
            result=st.executeQuery();
            Tablamodelo.addColumn("Cargo");
            Tablamodelo.addColumn("Max(l.Salario)");
            while(result.next()){
                Tablamodelo.addRow(new Object[]{result.getString("Cargo"),result.getString("Max(l.Salario)")});
            }
        }catch(Exception x){
            JOptionPane.showMessageDialog(null,"Conexión fallida","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConsulta3ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        if (JOptionPane.showConfirmDialog(this, "¿Desea cerrar la aplicacion?", 
            "Salir", JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null,"Tenga un feliz dia!!");
            dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProyectoConstruccionColombia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProyectoConstruccionColombia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProyectoConstruccionColombia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProyectoConstruccionColombia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProyectoConstruccionColombia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla1;
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnConsulta1;
    private javax.swing.JButton btnConsulta2;
    private javax.swing.JButton btnConsulta3;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label1;
    // End of variables declaration//GEN-END:variables
}
